config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  
  resources :users
  resources :bookmarks do
    member do
      post :like
      post :unlike
    end
  end
  
  get 'welcome/index'

  get 'about' => 'welcome#about'

  post :incoming, to: 'bookmarks#create'
  root to: "welcome#index"
  
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  
  markable_as :liked
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable, :omniauth_providers => [:facebook]
  
  has_many :bookmarks
  
  acts_as_marker
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email     = auth.info.email
      user.password  = Devise.friendly_token[0,20]
      user.name      = auth.info.name
      user.image     = auth.info.image
      user.skip_confirmation!
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  
  skip_before_action :verify_authenticity_token, only: [:create]
  before_action :bookmark_id, only: [:destroy, :like, :unlike]
  
  def index
    bookmarks = Bookmark.all
    @bookmarks = bookmarks.group_by(&:topic)
    authorize @bookmarks
  end
  
  def show
    @bookmarks = Bookmark.where(topic: params[:id])
  end
  
  def create
    CreateBookmark.call(params)
    head 200
  end
  
  
  def destroy    
    if @bookmark.destroy
      flash[:notice] = "Bookmark deleted!"
    else
      flash[:alert] = "An error occurred, please try again!"
    end
    
    redirect_to user_path
  end
  
    
  def like
    current_user.set_mark :liked, @bookmark
    redirect_to :back
  end
  
  def unlike
    current_user.remove_mark :liked, @bookmark
    redirect_to :back
  end
  
  protected
  
  def bookmark_id
    @bookmark = Bookmark.find(params[:id])
  end
  
  private
  
  def bookmark_params
    params.require(:bookmark).permit(:url, :topic, :title, :description, :favicon)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    
    if @user.persisted?
      @user.skip_confirmation!
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @bookmarks = current_user.bookmarks.group_by(&:topic)
    @liked = current_user.liked_bookmarks.group_by(&:topic)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def default_favicon(bookmark)
    bookmark.favicon == "" ? image_tag('default.png') : image_tag("#{bookmark.favicon}")
  end
  
  def url_fixer(url)
   /^http/i.match(url) ? url : "http://#{url}"
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_bookmark.html.haml
- bookmarks.each do |bookmark|
  .col-md-6.bookmark.text-center
    %h4
      = link_to "#{bookmark.title}", url_fixer(bookmark.url), class: 'livepreview'
      = default_favicon(bookmark)
    %p 
      "#{bookmark.description}"
      - if bookmark.marked_as? :liked, by: current_user
        = link_to unlike_bookmark_path(bookmark), method: :post, class: 'btn btn-default' do
          %i.fa.fa-heart-o  
      - unless bookmark.marked_as? :liked, by: current_user || bookmark.user == current_user
        = link_to like_bookmark_path(bookmark), method: :post, class: 'btn btn-default' do
          %i.fa.fa-heart
      - if policy(bookmark).destroy?
        = link_to "Delete", bookmark_path(bookmark), method: :delete, class: 'btn btn-danger'

app/views/bookmarks/_bookmarks.html.haml
.col-md-8.bookmark-category
  - @bookmarks.each_pair do |topic, bookmarks|
    .col-md-12.topic
      %br
      %br
      %br
      = link_to "#{topic}", bookmark_path(topic), class: 'btn btn-default'
      %br
      %br
      %br
      = render partial: 'bookmarks/bookmark', locals: {bookmarks: bookmarks}

app/views/bookmarks/_preview.html.haml
.col-md-4
  .preview-window
    %h4.text-center
      Live Preview
    .thumbnail
      = holder_tag '300x240', 'Hover over link for preview!', 'sky', id: 'holder'

app/views/bookmarks/index.html.haml
= render partial: 'bookmarks'
= render partial: 'preview'

app/views/bookmarks/show.html.haml
- @bookmarks.each do |bookmark|
  .col-md-6.bookmark.text-center
    %h4
      = link_to "#{bookmark.title}", url_fixer(bookmark.url), class: 'livepreview'
      = default_favicon(bookmark)
    %p 
      "#{bookmark.description}"
      - if bookmark.user != current_user
        = link_to like_bookmark_path(bookmark), method: :post, class: 'btn btn-default' do
          %i.fa.fa-heart
      - if policy(bookmark).destroy?
        = link_to "Delete", bookmark_path(bookmark), method: :delete, class: 'btn btn-danger'
= render partial: 'preview'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SaveIt
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      .flash
        - if flash[:notice]
          .alert.alert-success
            .button.close{:data => {:dismiss => "alert"} } 
            = flash[:notice]
        - elsif flash[:error]
          .alert.alert-danger
            .button.close{:data => {:dismiss => "alert"} } 
            = flash[:error]
        - elsif flash[:alert]
          .alert.alert-warning
            .button.close{:data => {:dismiss => "alert"} } 
            = flash[:alert]

      - if current_user
        .navbar.navbar-default.navbar-fixed-top
          %ul.nav.navbar-nav
            = link_to "My Bookmarks", user_path(current_user), class: 'navbar-brand'
            = link_to "All Bookmarks", bookmarks_path, class: 'navbar-brand'
            = link_to "My Account", edit_user_registration_path, class: 'navbar-brand'
            = link_to "About", about_path, class: 'navbar-brand'
            = link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'navbar-brand'
          
      = yield
      

app/views/users/_liked.html.haml
.col-md-8.liked-bookmarks
  %h4 Liked Bookmarks
  - @liked.each_pair do |topic, bookmarks|
    .col-md-12.topic
      %br
      = link_to "#{topic}", bookmark_path(topic), class: 'btn btn-default'
      %br
      %br
      %br
      = render partial: 'bookmarks/bookmark', locals: {bookmarks: bookmarks}

app/views/users/show.html.haml
.col-md-4.col-md-offset-2.text-center.user-greeting
  = "Hello #{current_user.name}!"
  - if current_user.image.present?
    = image_tag "#{current_user.image}"
  %h3 Instructions:
  %p
    To create a new bookmark, send an email
    = mail_to "bookmarks@app32619189.mailgun.org", "here."
    For the subject line, type the topic of the bookmark.
    For the body of the email, type the full address of the website.
  %br
= render partial: 'bookmarks/bookmarks'
= render partial: 'bookmarks/preview'
- if @liked.any?
  = render partial: 'liked'

app/views/welcome/about.html.haml
.about.text-center
  %h1 SaveIt is a social bookmarking utility!
  %br
  %p It allows users to submit bookmarks by email that are automatically categorized and sorted by topic.
  %br
  %p Users can sign up via email or by using a Facebook account.
  %br
  %p
    SaveIt features a live preview window for bookmarks utilized by the
    = link_to '(Jquery Live Link plugin).', 'https://github.com/alanphoon/jquery-live-preview'

app/views/welcome/index.html.haml
.container-full
  .row
    .col-lg-12.text-center.v-center
      %h1.title Welcome to SaveIt!
      %p.lead a social bookmarking site
      %br
      = link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'
      = link_to "Sign In", user_session_path, class: 'btn btn-primary'
      %br
      %br
      = link_to user_omniauth_authorize_path(:facebook), class: 'btn btn-social btn-md btn-facebook' do
        %i.fa.fa-facebook
        Sign in with Facebook
  / /row
  .row
    .col-lg-12.text-center.v-center{:style => "font-size:39pt;"}
  %br
  %br
  %br
  %br
  %br
/ /container full
.container
  %hr/
  .row
    .col-md-4
      .panel.panel-default
        .panel-heading
          %h3.text-center Share!
        .panel-body
          SaveIt makes it easy to share your bookmarks with others! SaveIt lets users email bookmarks to the site which are           automatically categorized by topic. Users can like and unlike bookmarks that are shared by others!
    .col-md-4
      .panel.panel-default
        .panel-heading
          %h3.text-center Preview!
        .panel-body
          SaveIt features a live preview window embedded into the site! See links without ever having to leave the page!
    .col-md-4
      .panel.panel-default
        .panel-heading
          %h3.text-center Auto-magic!
        .panel-body
          As soon as SaveIt receives an email from a user, it automatically pulls information from the each link. A title,
          icon, and description are auto-magically added to the Bookmark link. We take care of all the work for you!
  .row
    .col-lg-12
      %br
      %br
      %p.pull-right
          Created by Austin Sisson
      %br
      %br